version: '3.8'
services:
  mount_name:
    image: t3nk3y/bees
    privileged: true
    restart: unless-stopped
    hostname: beesd
    environment:
      - HASH_TABLE=/mnt/.beeshome/beeshash.dat
      - HASH_TABLE_SIZE=128K
      - OPTIONS=-a -v 6
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - /path/to/btrfs/mount:/mnt

  another_mount_name:
    image: t3nk3y/bees
    privileged: true
    restart: unless-stopped
    hostname: beesd
    environment:
      - HASH_TABLE=/mnt/.beeshome/beeshash.dat
      - HASH_TABLE_SIZE=128K
      - OPTIONS=-a -v 6
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - /path/to/btrfs/another_mount:/mnt
